apiVersion: v1
kind: Service
metadata:
  name: rabbit
spec:
  selector:
    app: k8s-rabbit
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
    - protocol: TCP
      port: 15672
      targetPort: 15672
  type: NodePort