apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbit-deployment
  labels:
    app: k8s-app
spec:
  selector:
    matchLabels:
      app: k8s-rabbit
  template:
    metadata:
      labels:
        app: k8s-rabbit
    spec:
      containers:
        - name: rabbit
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
